# server:
#   port: 8084

# cluster.name: sitcker-cluster
# node.name: node_001
# node.roles: [data, master, ingest]

# network.host: https://8063c2e7a91f4814b6c492ee9cc9283c.us-west-2.aws.found.io:443
# http.port: 9200
# transport.tcp.port: 9300

# discovery.zen.ping.unicast.hosts: ["node-01_ip:9300","node-02_ip:9300","node-03_ip:9300","node-04_ip:9300"]
# cluster.initial_master_nodes:
#         - node_name-1
#         - node_name-2
#         - node_name-3

# http.cors.enabled: true
# http.cors.allow-origin: "*"

# bootstrap.memory_lock: true
# indices.fielddata.cache.size: 65%

# xpack.monitoring.enabled: true
# xpack.monitoring.collection.enabled: true

# eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka